[tool.poetry]
name = "test-grupo-natureza"
version = "0.1.0"
description = ""
authors = ["Leonardo"]
readme = "README.md"
packages = [{include = "test_grupo_natureza"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
